#!/bin/bash

#source /glade/p/work/kdagon/ncar_pylib_clone/bin/activate

#niter=10
#echo "number of samples = "$niter

# Run LHC_write to generate parameter value array
# only needs to be run once for the ensemble
# needs to be run before LHC_read_nl.py
# command line arg provides number of samples/simulations
#python LHC_write.py $niter

i=1

#python LHC_read_nl.py $(( i - 1 )) >> nl_test

export USER="kdagon"
export NAME="hydro_ensemble"
export EXPTNAME=${NAME}_$i

pftfile="/glade/u/home/$USER/pft_files/hydro_ensemble_LHC/${EXPTNAME}.nc"
cp /glade/p/cesmdata/cseg/inputdata/lnd/clm2/paramdata/clm5_params.c171117.nc $pftfile

uclm="paramfile='$pftfile'"
echo  $uclm >> user_nl_clm
